[profile.default]
solc_version = '0.8.25'
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 10_000_000
# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = true

via_ir = true
fuzz_runs = 500
deny_warnings = false

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

